### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by sungwonida** [M157q/linkedin2md#9]
I ran into this issue by using the command 'linkedin2md <my_linkedin_id>' as my linkedin id starts with 33292...
Same with sudo.

```
Traceback (most recent call last):
  File "/usr/local/bin/linkedin2md", line 4, in <module>
    __import__('pkg_resources').run_script('linkedin2md==0.0.1', 'linkedin2md')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1507, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/linkedin2md-0.0.1-py3.6.egg/EGG-INFO/scripts/linkedin2md", line 6, in <module>
  File "/usr/local/lib/python3.6/site-packages/linkedin2md-0.0.1-py3.6.egg/linkedin2md/linkedin2md.py", line 217, in main
  File "/usr/local/lib/python3.6/site-packages/linkedin2md-0.0.1-py3.6.egg/linkedin2md/linkedin2md.py", line 30, in get_profile_page_html
  File "/usr/local/lib/python3.6/site-packages/dryscrape-1.0-py3.6.egg/dryscrape/session.py", line 22, in __init__
  File "/usr/local/lib/python3.6/site-packages/dryscrape-1.0-py3.6.egg/dryscrape/driver/webkit.py", line 30, in __init__
  File "/usr/local/lib/python3.6/site-packages/webkit_server.py", line 230, in __init__
    self.conn = connection or ServerConnection()
  File "/usr/local/lib/python3.6/site-packages/webkit_server.py", line 507, in __init__
    self._sock = (server or get_default_server()).connect()
  File "/usr/local/lib/python3.6/site-packages/webkit_server.py", line 450, in get_default_server
    _default_server = Server()
  File "/usr/local/lib/python3.6/site-packages/webkit_server.py", line 416, in __init__
    stderr = subprocess.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```
Please help.

**Comment by fkztw** [comment]
@sungwonida I think the problem might be the permission settings of the `webkit_server` is incorrect. I guess it's location is `/usr/local/lib/python3.6/site-packages/webkit_server` in your computer. Check if it got the right permission for your user, group and make sure you have the permission to execute it. (`sudo chmod +x /usr/local/lib/python3.6/site-packages/webkit_server` might help)

BTW, I have to tell you that this program currently doesn't work because of #8

**Comment by sungwonida** [comment]
Ah. I got it. Thanks for letting me know that.
